# -*- coding: utf-8 -*-
"""OpenEndedCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCGOjZkLuaOK4vSg3usHcqG1x0GB985q
"""

# ==============================
# 1. INSTALL & IMPORT LIBRARIES
# ==============================
!pip install -q transformers evaluate nltk rouge-score bert-score

import torch
import pandas as pd
import numpy as np
import re
import io
import requests
from PIL import Image, UnidentifiedImageError
from pathlib import Path
from tqdm import tqdm

from transformers import (
    InstructBlipProcessor,
    InstructBlipForConditionalGeneration
)

import evaluate
from nltk.translate.meteor_score import meteor_score
from sklearn.metrics.pairwise import cosine_similarity

import nltk
nltk.download("wordnet")
nltk.download("omw-1.4")

from google.colab import drive
drive.mount("/content/drive")

# 2. PATHS & CONFIG
# ==============================
EXCEL_PATH = "/content/drive/MyDrive/VQA/VQA_RAD_Head_Only.xlsx"
IMAGES_DIR = "/content/drive/MyDrive/VQA/VQA_RAD_Images"
GLOVE_PATH = "/content/drive/MyDrive/VQA/glove.6B.300d.txt"

MODEL_NAME = "Salesforce/instructblip-flan-t5-xl"
MAX_TOKENS = 64
TOP_K_KEYWORDS = 5

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 3. LOAD METRICS
# ==============================
rouge = evaluate.load("rouge")
bert_f1 = evaluate.load("bertscore")

# 4. LOAD GLOVE
# ==============================
def load_glove(path):
    glove = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            parts = line.strip().split()
            word = parts[0]
            vector = np.array(parts[1:], dtype=np.float32)
            glove[word] = vector
    return glove

glove = load_glove(GLOVE_PATH)
print("GloVe loaded:", len(glove))

vocab_words = list(glove.keys())
vocab_vectors = np.stack(list(glove.values()))

# 5. QUESTION → KEYWORDS
# ==============================
def question_embedding(question):
    tokens = question.lower().split()
    vectors = [glove[t] for t in tokens if t in glove]
    if len(vectors) == 0:
        return np.zeros(300)
    return np.mean(vectors, axis=0)

def extract_keywords(question, k=5):
    q_vec = question_embedding(question).reshape(1, -1)
    similarities = cosine_similarity(q_vec, vocab_vectors)[0]
    top_idx = similarities.argsort()[-k:][::-1]
    return [vocab_words[i] for i in top_idx]

def build_prompt(question, keywords):
    return f"Keywords: {', '.join(keywords)}. Question: {question}"

# ==============================
# 6. LOAD MODEL
# ==============================
processor = InstructBlipProcessor.from_pretrained(MODEL_NAME, use_fast=True)
model = InstructBlipForConditionalGeneration.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16
).to(DEVICE)

model.eval()

# ==============================
# 7. LOAD DATA
# ==============================
df = pd.read_excel(EXCEL_PATH)
print("Total samples:", len(df))

# 8. IMAGE LOADER
# ==============================
def load_image(image_id):
    filename = Path(image_id).name
    img_path = Path(IMAGES_DIR) / filename

    try:
        if not img_path.exists():
            if image_id.startswith("http"):
                response = requests.get(image_id, timeout=15)
                response.raise_for_status()
                image = Image.open(io.BytesIO(response.content)).convert("RGB")
                image.save(img_path)
            else:
                raise FileNotFoundError

        return Image.open(img_path).convert("RGB")

    except (UnidentifiedImageError, OSError, ValueError):
        return None

# 9. INFERENCE LOOP
# ==============================
predictions = []
references = []

for _, row in tqdm(df.iterrows(), total=len(df)):
    image = load_image(row["IMAGEID"])
    if image is None:
        continue

    question = row["QUESTION"]
    gt_answer = row["ANSWER"]

    keywords = extract_keywords(question, TOP_K_KEYWORDS)
    prompt = build_prompt(question, keywords)

    inputs = processor(
        images=image,
        text=prompt,
        return_tensors="pt"
    ).to(DEVICE)

    with torch.no_grad():
        output = model.generate(**inputs, max_length=MAX_TOKENS)

    pred_answer = processor.decode(
        output[0],
        skip_special_tokens=True
    )

    predictions.append(pred_answer)
    references.append(gt_answer)

print("Predictions generated:", len(predictions))

# 10. OPEN-ENDED ACCURACY
# ==============================
def normalize_answer(text):
    text = str(text).lower().strip()
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text

correct = 0
total = len(predictions)

for pred, ref in zip(predictions, references):
    if normalize_answer(pred) == normalize_answer(ref):
        correct += 1

open_ended_accuracy = correct / total

#METEOR
meteor_scores = [
    meteor_score([ref.split()], pred.split())
    for ref, pred in zip(references, predictions)
]

# ROUGE
rouge_score = rouge.compute(
    predictions=predictions,
    references=references
)

# BERTScore
bert_scores = bert_f1.compute(
    predictions=predictions,
    references=references,
    lang="en"
)

# 12.ACCURACY
# ==============================
bert_f1_scores = bert_scores["f1"]

soft_correct = sum(f1 >= 0.8 for f1 in bert_f1_scores)
soft_accuracy = soft_correct / len(bert_f1_scores)

print("\n===== OPEN-ENDED VQA RESULTS =====")
print(f"Exact Match Accuracy : {open_ended_accuracy * 100:.2f}%")
print(f"Accuracy (BERT≥0.8): {soft_accuracy * 100:.2f}%")
#print(f"METEOR               : {np.mean(meteor_scores):.4f}")
print(f"ROUGE-L              : {rouge_score['rougeL']:.4f}")
print(f"BERT-F1              : {np.mean(bert_scores['f1']):.4f}")