# -*- coding: utf-8 -*-
"""VQA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yAspE8Aybq5LeJQj_lpx6iekTSRhP1sD
"""

from google.colab import drive
drive.mount('/content/drive')

base_path = "/content/drive/MyDrive/MedicalVQA"

import zipfile
import os

def unzip(zip_path, extract_to):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_to)

os.makedirs("data", exist_ok=True)

unzip(f"{base_path}/VQA-RAD.zip", "data/vqa-rad")
unzip(f"{base_path}/SLAKE.zip", "data/slake")
unzip(f"{base_path}/Path_VQA.zip", "data/pathvqa")

import shutil
import os

# VQA-RAD
if os.path.exists("data/vqa-rad/VQA_RAD Image Folder"):
    shutil.move("data/vqa-rad/VQA_RAD Image Folder", "data/vqa-rad/images")

if os.path.exists("data/vqa-rad/VQA_RAD Dataset Public.json"):
    os.rename("data/vqa-rad/VQA_RAD Dataset Public.json",
              "data/vqa-rad/train.json")

# SLAKE
if os.path.exists("data/slake/Slake1.0"):
    shutil.move("data/slake/Slake1.0/imgs", "data/slake/imgs")
    shutil.move("data/slake/Slake1.0/validate.json", "data/slake/val.json")
    shutil.move("data/slake/Slake1.0/test.json", "data/slake/test.json")
    shutil.rmtree("data/slake/Slake1.0")

# PMC-VQA
if os.path.exists("data/pathvqa/pathVqaData"):
    shutil.move("data/pathvqa/pathVqaData/textbook_of_pathology_image",
                "data/pathvqa/images")

    os.rename("data/pathvqa/pathVqaData/QA_pairs_vb.json",
              "data/pathvqa/train.json")

    shutil.rmtree("data/pathvqa/pathVqaData")

print("Done")

import json
from sklearn.model_selection import train_test_split

def normalize(text):
    return str(text).lower().strip()

def get_type(ans):
    ans = ans.lower()
    if ans in ["yes", "no"]:
        return "closed"
    elif len(ans.split()) <= 2:
        return "closed"
    else:
        return "open"

def process_vqarad():
    data = json.load(open("data/vqa-rad/train.json"))
    image_dir = "data/vqa-rad/images"

    processed = []

    for item in data:
        try:
            answer = normalize(item["answer"])

            processed.append({
                "image": os.path.join(image_dir, item["image_name"]),
                "question": normalize(item["question"]),
                "answer": answer,
                "type": get_type(answer)
            })
        except:
            continue

    return processed

def process_slake():
    val = json.load(open("data/slake/val.json"))
    test = json.load(open("data/slake/test.json"))

    data = val + test
    image_dir = "data/slake/imgs"

    processed = []

    for item in data:
        try:
            # keep only English
            if item.get("q_lang", "en") != "en":
                continue

            answer = normalize(item["answer"])

            # ✅ FIXED LINE
            img_path = os.path.join(image_dir, item["img_name"])

            processed.append({
                "image": img_path,
                "question": normalize(item["question"]),
                "answer": answer,
                "type": get_type(answer)
            })

        except Exception as e:
            continue

    return processed

import re

def extract_number(text):
    numbers = re.findall(r"\d+", text)
    if len(numbers) > 0:
        return numbers[0]
    return None

def process_pathvqa():
    import json
    import os

    data = json.load(open("data/pathvqa/train.json"))
    image_dir = "data/pathvqa/images"

    processed = []

    for item in data:
        try:
            # clean text
            question = str(item["Questions"]).lower().strip()
            answer = str(item["Answers"]).lower().strip()

            # 🔥 STEP A: extract number
            number = extract_number(item["Image_ID"])

            # skip if no number
            if number is None:
                continue

            # 🔥 STEP B: create correct filename
            img_name = "img_" + number + ".jpg"

            # 🔥 STEP C: full path
            img_path = os.path.join(image_dir, img_name)

            # 🔥 STEP D: check file exists
            if not os.path.exists(img_path):
                continue

            # save
            processed.append({
                "image": img_path,
                "question": question,
                "answer": answer,
                "type": "closed" if answer in ["yes", "no"] else "open"
            })

        except:
            continue

    return processed

path = process_pathvqa()

print("Total Path samples:", len(path))

from sklearn.model_selection import train_test_split
import json
import os

def save_split(data, save_dir):
    os.makedirs(save_dir, exist_ok=True)

    train, val = train_test_split(data, test_size=0.2, random_state=42)

    json.dump(train, open(f"{save_dir}/train.json", "w"), indent=2)
    json.dump(val, open(f"{save_dir}/val.json", "w"), indent=2)

save_split(path, "processed/pathvqa")

def save_split(data, save_dir):
    os.makedirs(save_dir, exist_ok=True)

    train, val = train_test_split(data, test_size=0.2, random_state=42)

    json.dump(train, open(f"{save_dir}/train.json", "w"), indent=2)
    json.dump(val, open(f"{save_dir}/val.json", "w"), indent=2)

vqa = process_vqarad()
save_split(vqa, "processed/vqa-rad")

slake = process_slake()
save_split(slake, "processed/slake")

pmc = process_pathvqa()
save_split(pmc, "processed/pathvqa")

print("Processed")

from torchvision import transforms

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

import torch

def load_glove(path):
    glove = {}
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            values = line.split()
            word = values[0]
            vector = torch.tensor([float(x) for x in values[1:]])
            glove[word] = vector
    return glove

glove_path = "/content/drive/MyDrive/MedicalVQA/glove.6B.300d.txt"
glove = load_glove(glove_path)

import re

def preprocess_question(q):
    q = q.lower()
    q = re.sub(r"[^a-z0-9 ]", "", q)
    return q.split()

def glove_question_embedding(question):
    tokens = preprocess_question(question)

    vectors = []
    for t in tokens:
        if t in glove:
            vectors.append(torch.tensor(glove[t]))

    if len(vectors) == 0:
        return torch.zeros(300)

    return torch.stack(vectors).mean(dim=0)

batch = next(iter(vqa_loader))

print(batch["question_vec"].shape)
print(type(batch["question_vec"]))

from torch.utils.data import Dataset
from PIL import Image

class MedicalVQADataset(Dataset):
    def __init__(self, json_path):
        self.data = json.load(open(json_path))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]

        image = Image.open(item["image"]).convert("RGB")
        image = transform(image)

        question_vec = glove_question_embedding(item["question"])

        return {
            "image": image,
            "question_vec": question_vec,
            "question": item["question"],
            "answer": item["answer"],
            "type": item["type"]
        }

def collate_fn(batch):
    return {
        "image": torch.stack([x["image"] for x in batch]),
        "question_vec": torch.stack([x["question_vec"] for x in batch]),
        "question": [x["question"] for x in batch],
        "answer": [x["answer"] for x in batch],
        "type": [x["type"] for x in batch]
    }

vqa_train   = MedicalVQADataset("processed/vqa-rad/train.json")
slake_train = MedicalVQADataset("processed/slake/train.json")
path_train   = MedicalVQADataset("processed/pathvqa/train.json")

from torch.utils.data import DataLoader

vqa_loader = DataLoader(vqa_train, batch_size=8, shuffle=True, collate_fn=collate_fn)
slake_loader = DataLoader(slake_train, batch_size=8, shuffle=True, collate_fn=collate_fn)
path_loader = DataLoader(path_train, batch_size=8, shuffle=True, collate_fn=collate_fn)

batch = next(iter(vqa_loader))
print("VQA:", batch["image"].shape)

batch = next(iter(slake_loader))
print("SLAKE:", batch["image"].shape)

batch = next(iter(path_loader))
print("PATH:", batch["image"].shape)



#implentation of code

!pip install timm torch-geometric scikit-learn

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import re

import timm

from torch.utils.data import DataLoader
from torch_geometric.data import Data
from torch_geometric.nn import GCNConv, global_mean_pool
from sklearn.neighbors import NearestNeighbors

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

def load_glove(path):
    glove = {}
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            values = line.split()
            word = values[0]
            vector = np.array(values[1:], dtype=np.float32)
            glove[word] = vector
    return glove

glove_path = "/content/drive/MyDrive/MedicalVQA/glove.6B.300d.txt"
glove = load_glove(glove_path)

print("Loaded words:", len(glove))

def preprocess_question(q):
    q = q.lower()
    q = re.sub(r"[^a-z0-9 ]", "", q)
    return q.split()

def question_to_vec(question, dim=300):
    tokens = preprocess_question(question)

    vecs = []
    for t in tokens:
        if t in glove:
            vectors.append(torch.tensor(glove[t]))

    if len(vecs) == 0:
        return torch.zeros(dim)

    return torch.tensor(vecs).mean(dim=0)

batch = next(iter(vqa_loader))

print(batch["question_vec"].shape)
print(type(batch["question_vec"]))

swin = timm.create_model(
    'swin_tiny_patch4_window7_224',
    pretrained=True
)

swin.head = nn.Identity()
swin = swin.to(device)
swin.eval()

def extract_patches(images):
    with torch.no_grad():
        feats = swin.forward_features(images)
    return feats  # [B, 49, 768]

def build_graph(node_feats, k=5):
    feats = node_feats.cpu().numpy()

    nbrs = NearestNeighbors(n_neighbors=k+1).fit(feats)
    _, idxs = nbrs.kneighbors(feats)

    edges = []
    for i in range(len(feats)):
        for j in idxs[i]:
            if i != j:
                edges.append([i, j])
                edges.append([j, i])

    return torch.tensor(edges).t().contiguous()

class QGNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.node_proj = nn.Linear(768, 300)
        self.q_proj = nn.Linear(300, 300)

        self.gcn1 = GCNConv(600, 256)
        self.gcn2 = GCNConv(256, 256)

    def forward(self, x, edge_index, q_embed):
        x = self.node_proj(x)

        q = self.q_proj(q_embed)
        q_expand = q.unsqueeze(0).expand(x.size(0), -1)

        x = torch.cat([x, q_expand], dim=1)

        x = F.relu(self.gcn1(x, edge_index))
        x = self.gcn2(x, edge_index)

        return x

class ClosedModel(nn.Module):
    def __init__(self, qgnn):
        super().__init__()
        self.qgnn = qgnn
        self.fc = nn.Linear(256, 2)

    def forward(self, data):
        node_emb = self.qgnn(data.x, data.edge_index, data.q_embed)

        batch = torch.zeros(node_emb.size(0), dtype=torch.long).to(device)
        graph_emb = global_mean_pool(node_emb, batch)

        return self.fc(graph_emb)

def extract_keywords(node_emb, top_k=3):
    importance = node_emb.mean(dim=1)
    top_idx = torch.topk(importance, top_k).indices

    return [f"region_{i.item()}" for i in top_idx]

def generate_answer(keywords):
    return f"Image shows {keywords[0]} and {keywords[1]}"

qgnn = QGNN().to(device)
model = ClosedModel(qgnn).to(device)

batch = next(iter(vqa_loader))

images = batch["image"].to(device)

q_vec = batch["question_vec"].to(device)

patches = extract_patches(images)

# ✅ FIX APPLIED HERE
x = patches[0].reshape(-1, patches.shape[-1])

q = q_vec[0]

print("Patch shape:", x.shape)  # should be [49, 768]

edge_index = build_graph(x)

data = Data(x=x, edge_index=edge_index)
data.q_embed = q.to(device)

logits = model(data)
print(logits)

node_emb = qgnn(x, edge_index, q)
keywords = extract_keywords(node_emb)

print("Keywords:", keywords)

#VQA-RAD CLOSE ENDED QUESTIONS

def get_closed_indices(batch):
    return [i for i, t in enumerate(batch["type"]) if t == "closed"]

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

from tqdm import tqdm

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

epochs = 10

for epoch in range(epochs):
    model.train()

    total_loss = 0
    correct = 0
    total = 0

    pbar = tqdm(vqa_loader, desc=f"Epoch {epoch+1}")

    for batch in pbar:

        images = batch["image"].to(device)
        q_vec = batch["question_vec"].to(device)
        types = batch["type"]
        answers = batch["answer"]

        patches = extract_patches(images)

        for i in range(len(images)):

            if types[i] != "closed":
                continue

            x = patches[i].reshape(-1, patches.shape[-1])
            q = q_vec[i]

            edge_index = build_graph(x)

            data = Data(x=x, edge_index=edge_index)
            data.q_embed = q

            label = 1 if answers[i] == "yes" else 0
            label = torch.tensor([label]).to(device)

            optimizer.zero_grad()

            logits = model(data)
            loss = criterion(logits, label)

            loss.backward()
            optimizer.step()

            total_loss += loss.item()

            pred = torch.argmax(logits, dim=1)
            correct += (pred == label).sum().item()
            total += 1

        # 🔥 LIVE UPDATE
        if total > 0:
            pbar.set_postfix({
                "loss": f"{total_loss:.2f}",
                "acc": f"{correct/total:.3f}"
            })

    epoch_acc = correct / total if total > 0 else 0

    print(f"\nEpoch {epoch+1} Summary")
    print("Total Loss:", total_loss)
    print("Accuracy:", epoch_acc)

print("Total samples in dataset:", len(vqa_loader.dataset))

closed_count = 0

for batch in vqa_loader:
    types = batch["type"]
    for t in types:
        if t == "closed":
            closed_count += 1

print("Closed questions used for training:", closed_count)

batch = next(iter(vqa_loader))

for i in range(5):
    print("Q:", batch["question"][i])
    print("A:", batch["answer"][i])
    print("Type:", batch["type"][i])
    print("-" * 40)

closed_questions = []

for batch in vqa_loader:
    for q, t in zip(batch["question"], batch["type"]):
        if t == "closed":
            closed_questions.append(q)

print("Total closed questions:", len(closed_questions))
print("\nSample questions:")
for q in closed_questions[:10]:
    print(q)

with open("closed_questions.txt", "w") as f:
    for q in closed_questions:
        f.write(q + "\n")

model.eval()

batch = next(iter(vqa_loader))

images = batch["image"].to(device)
q_vec = batch["question_vec"].to(device)
answers = batch["answer"]
types = batch["type"]

patches = extract_patches(images)

for i in range(len(images)):
    if types[i] != "closed":
        continue

    x = patches[i].reshape(-1, patches.shape[-1])
    q = q_vec[i]

    edge_index = build_graph(x)

    data = Data(x=x, edge_index=edge_index)
    data.q_embed = q

    logits = model(data)
    pred = torch.argmax(logits, dim=1).item()

    pred_text = "yes" if pred == 1 else "no"

    print("Q:", batch["question"][i])
    print("True:", answers[i])
    print("Pred:", pred_text)
    print("-" * 50)

from torch.utils.data import random_split

dataset = vqa_loader.dataset

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

print("Train size:", len(train_dataset))
print("Val size:", len(val_dataset))

train_loader = DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True,
    collate_fn=collate_fn
)

val_loader = DataLoader(
    val_dataset,
    batch_size=8,
    shuffle=False,
    collate_fn=collate_fn
)

from tqdm import tqdm

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

epochs = 5

for epoch in range(epochs):

    # 🔥 TRAIN
    model.train()
    train_correct = 0
    train_total = 0

    pbar = tqdm(train_loader, desc=f"Train Epoch {epoch+1}")

    for batch in pbar:

        images = batch["image"].to(device)
        q_vec = batch["question_vec"].to(device)
        types = batch["type"]
        answers = batch["answer"]

        patches = extract_patches(images)

        for i in range(len(images)):

            if types[i] != "closed":
                continue

            x = patches[i].reshape(-1, patches.shape[-1])
            q = q_vec[i]

            edge_index = build_graph(x)

            data = Data(x=x, edge_index=edge_index)
            data.q_embed = q

            label = 1 if answers[i] == "yes" else 0
            label = torch.tensor([label]).to(device)

            optimizer.zero_grad()

            logits = model(data)
            loss = criterion(logits, label)

            loss.backward()
            optimizer.step()

            pred = torch.argmax(logits, dim=1)
            train_correct += (pred == label).sum().item()
            train_total += 1

        if train_total > 0:
            pbar.set_postfix({"train_acc": f"{train_correct/train_total:.3f}"})

    train_acc = train_correct / train_total if train_total > 0 else 0

    # 🔥 VALIDATION
    model.eval()
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for batch in tqdm(val_loader, desc="Validation"):

            images = batch["image"].to(device)
            q_vec = batch["question_vec"].to(device)
            types = batch["type"]
            answers = batch["answer"]

            patches = extract_patches(images)

            for i in range(len(images)):

                if types[i] != "closed":
                    continue

                x = patches[i].reshape(-1, patches.shape[-1])
                q = q_vec[i]

                edge_index = build_graph(x)

                data = Data(x=x, edge_index=edge_index)
                data.q_embed = q

                label = 1 if answers[i] == "yes" else 0
                label = torch.tensor([label]).to(device)

                logits = model(data)

                pred = torch.argmax(logits, dim=1)
                val_correct += (pred == label).sum().item()
                val_total += 1

    val_acc = val_correct / val_total if val_total > 0 else 0

    print(f"\nEpoch {epoch+1}")
    print("Train Accuracy:", train_acc)
    print("Validation Accuracy:", val_acc)

best_val = 0

# inside epoch loop AFTER val_acc calculation
if val_acc > best_val:
    best_val = val_acc
    torch.save(model.state_dict(), "best_model.pth")
    print("🔥 Best model saved!")

#SLAKE CLOSED ENDED QUESTIONS

dataset = slake_loader.dataset

print("Total SLAKE samples:", len(dataset))

from torch.utils.data import random_split

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

print("Train size:", len(train_dataset))
print("Val size:", len(val_dataset))

train_loader = DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True,
    collate_fn=collate_fn
)

val_loader = DataLoader(
    val_dataset,
    batch_size=8,
    shuffle=False,
    collate_fn=collate_fn
)

qgnn = QGNN().to(device)
model = ClosedModel(qgnn).to(device)

from tqdm import tqdm

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

epochs = 5
best_val = 0

for epoch in range(epochs):

    # TRAIN
    model.train()
    train_correct = 0
    train_total = 0

    pbar = tqdm(train_loader, desc=f"Train Epoch {epoch+1}")

    for batch in pbar:

        images = batch["image"].to(device)
        q_vec = batch["question_vec"].to(device)
        types = batch["type"]
        answers = batch["answer"]

        patches = extract_patches(images)

        for i in range(len(images)):

            if types[i] != "closed":
                continue

            x = patches[i].reshape(-1, patches.shape[-1])
            q = q_vec[i]

            edge_index = build_graph(x)

            data = Data(x=x, edge_index=edge_index)
            data.q_embed = q

            label = 1 if answers[i] == "yes" else 0
            label = torch.tensor([label]).to(device)

            optimizer.zero_grad()

            logits = model(data)
            loss = criterion(logits, label)

            loss.backward()
            optimizer.step()

            pred = torch.argmax(logits, dim=1)
            train_correct += (pred == label).sum().item()
            train_total += 1

        if train_total > 0:
            pbar.set_postfix({"train_acc": f"{train_correct/train_total:.3f}"})

    train_acc = train_correct / train_total if train_total > 0 else 0

    # VALIDATION
    model.eval()
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for batch in tqdm(val_loader, desc="Validation"):

            images = batch["image"].to(device)
            q_vec = batch["question_vec"].to(device)
            types = batch["type"]
            answers = batch["answer"]

            patches = extract_patches(images)

            for i in range(len(images)):

                if types[i] != "closed":
                    continue

                x = patches[i].reshape(-1, patches.shape[-1])
                q = q_vec[i]

                edge_index = build_graph(x)

                data = Data(x=x, edge_index=edge_index)
                data.q_embed = q

                label = 1 if answers[i] == "yes" else 0
                label = torch.tensor([label]).to(device)

                logits = model(data)

                pred = torch.argmax(logits, dim=1)
                val_correct += (pred == label).sum().item()
                val_total += 1

    val_acc = val_correct / val_total if val_total > 0 else 0

    print(f"\nEpoch {epoch+1}")
    print("Train Accuracy:", train_acc)
    print("Validation Accuracy:", val_acc)

    # 🔥 save best
    if val_acc > best_val:
        best_val = val_acc
        torch.save(model.state_dict(), "best_slake_model.pth")
        print("🔥 Best SLAKE model saved!")

# ===============================
# SLAKE DATASET ANALYSIS (ALL-IN-ONE)
# ===============================

closed = 0
open_q = 0
all_questions = []
closed_questions = []

# ---- Count + Collect ----
for batch in slake_loader:
    for q, a, t in zip(batch["question"], batch["answer"], batch["type"]):
        all_questions.append(q)

        if t == "closed":
            closed += 1
            closed_questions.append(q)
        else:
            open_q += 1

# ---- Basic Stats ----
print("===== DATASET OVERVIEW =====")
print("Total questions:", len(all_questions))
print("Closed questions:", closed)
print("Open questions:", open_q)

# ---- Train / Validation Split ----
print("\n===== SPLIT INFO =====")
print("Train samples:", len(train_loader.dataset))
print("Validation samples:", len(val_loader.dataset))

# ---- Count closed in TRAIN ----
train_closed = 0
for batch in train_loader:
    for t in batch["type"]:
        if t == "closed":
            train_closed += 1

print("Closed questions used for training:", train_closed)

# ---- Sample Questions ----
print("\n===== SAMPLE QUESTIONS =====")
batch = next(iter(slake_loader))

for i in range(5):
    print("Q:", batch["question"][i])
    print("A:", batch["answer"][i])
    print("Type:", batch["type"][i])
    print("-" * 50)

# ---- Sample CLOSED Questions ----
print("\n===== SAMPLE CLOSED QUESTIONS =====")
for q in closed_questions[:10]:
    print(q)

# ---- Save Questions ----
with open("slake_closed_questions.txt", "w") as f:
    for q in closed_questions:
        f.write(q + "\n")

print("\n✅ Closed questions saved to file!")

# ---- MODEL PREDICTION CHECK ----
print("\n===== MODEL PREDICTIONS (VALIDATION) =====")

model.eval()

batch = next(iter(val_loader))

images = batch["image"].to(device)
q_vec = batch["question_vec"].to(device)
answers = batch["answer"]
types = batch["type"]

patches = extract_patches(images)

count = 0

for i in range(len(images)):
    if types[i] != "closed":
        continue

    x = patches[i].reshape(-1, patches.shape[-1])
    q = q_vec[i]

    edge_index = build_graph(x)

    data = Data(x=x, edge_index=edge_index)
    data.q_embed = q

    logits = model(data)
    pred = torch.argmax(logits, dim=1).item()

    pred_text = "yes" if pred == 1 else "no"

    print("Q:", batch["question"][i])
    print("True:", answers[i])
    print("Pred:", pred_text)
    print("-" * 60)

    count += 1
    if count == 5:
        break

#PATH VQA CLOSE ENDED QUESIONS

dataset = path_loader.dataset

print("Total Path-VQA samples:", len(dataset))

from torch.utils.data import random_split

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

print("Train size:", len(train_dataset))
print("Val size:", len(val_dataset))

train_loader = DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True,
    collate_fn=collate_fn
)

val_loader = DataLoader(
    val_dataset,
    batch_size=8,
    shuffle=False,
    collate_fn=collate_fn
)

qgnn = QGNN().to(device)
model = ClosedModel(qgnn).to(device)

from tqdm import tqdm

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

epochs = 10
best_val = 0

for epoch in range(epochs):

    # TRAIN
    model.train()
    train_correct = 0
    train_total = 0

    pbar = tqdm(train_loader, desc=f"Train Epoch {epoch+1}")

    for batch in pbar:

        images = batch["image"].to(device)
        q_vec = batch["question_vec"].to(device)
        types = batch["type"]
        answers = batch["answer"]

        patches = extract_patches(images)

        for i in range(len(images)):

            if types[i] != "closed":
                continue

            x = patches[i].reshape(-1, patches.shape[-1])
            q = q_vec[i]

            edge_index = build_graph(x)

            data = Data(x=x, edge_index=edge_index)
            data.q_embed = q

            label = 1 if answers[i] == "yes" else 0
            label = torch.tensor([label]).to(device)

            optimizer.zero_grad()

            logits = model(data)
            loss = criterion(logits, label)

            loss.backward()
            optimizer.step()

            pred = torch.argmax(logits, dim=1)
            train_correct += (pred == label).sum().item()
            train_total += 1

        if train_total > 0:
            pbar.set_postfix({"train_acc": f"{train_correct/train_total:.3f}"})

    train_acc = train_correct / train_total if train_total > 0 else 0

    # VALIDATION
    model.eval()
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for batch in tqdm(val_loader, desc="Validation"):

            images = batch["image"].to(device)
            q_vec = batch["question_vec"].to(device)
            types = batch["type"]
            answers = batch["answer"]

            patches = extract_patches(images)

            for i in range(len(images)):

                if types[i] != "closed":
                    continue

                x = patches[i].reshape(-1, patches.shape[-1])
                q = q_vec[i]

                edge_index = build_graph(x)

                data = Data(x=x, edge_index=edge_index)
                data.q_embed = q

                label = 1 if answers[i] == "yes" else 0
                label = torch.tensor([label]).to(device)

                logits = model(data)

                pred = torch.argmax(logits, dim=1)
                val_correct += (pred == label).sum().item()
                val_total += 1

    val_acc = val_correct / val_total if val_total > 0 else 0

    print(f"\nEpoch {epoch+1}")
    print("Train Accuracy:", train_acc)
    print("Validation Accuracy:", val_acc)

    # SAVE BEST MODEL
    if val_acc > best_val:
        best_val = val_acc
        torch.save(model.state_dict(), "best_path_model.pth")
        print("🔥 Best Path model saved!")

#Open ended code for VQA-RAD

# Map node positions to pseudo-anatomical regions
def map_to_region(idx):
    regions = [
        "upper region", "lower region", "central region",
        "left side", "right side",
        "anterior area", "posterior area"
    ]
    return regions[idx % len(regions)]


def extract_keywords(node_emb, top_k=3):
    scores = node_emb.norm(dim=1)
    top_idx = torch.topk(scores, top_k).indices

    keywords = [map_to_region(i.item()) for i in top_idx]
    return keywords

def generate_answer(keywords, question):
    q = question.lower()

    if "what" in q:
        return f"The image indicates abnormality in the {keywords[0]}."

    elif "where" in q:
        return f"The finding is located in the {keywords[0]}."

    elif "how many" in q:
        return f"Multiple regions are involved, including the {keywords[0]} and {keywords[1]}."

    else:
        return f"Relevant areas include the {', '.join(keywords)}."

model.eval()

found = 0

for batch in vqa_loader:

    images = batch["image"].to(device)
    q_vec = batch["question_vec"].to(device)
    questions = batch["question"]
    answers = batch["answer"]
    types = batch["type"]

    patches = extract_patches(images)

    for i in range(len(images)):

        if types[i] != "open":
            continue

        x = patches[i].reshape(-1, patches.shape[-1])
        q = q_vec[i]

        edge_index = build_graph(x)
        node_emb = qgnn(x, edge_index, q)

        keywords = extract_keywords(node_emb)
        pred = generate_answer(keywords, questions[i])

        print("Q:", questions[i])
        print("GT:", answers[i])
        print("Pred:", pred)
        print("-" * 60)

        found += 1

        if found == 5:
            break

    if found == 5:
        break

from nltk.translate.bleu_score import sentence_bleu

def compute_bleu(pred, gt):
    return sentence_bleu([gt.split()], pred.split())

bleu_scores = []

for batch in vqa_loader:

    images = batch["image"].to(device)
    q_vec = batch["question_vec"].to(device)
    questions = batch["question"]
    answers = batch["answer"]
    types = batch["type"]

    patches = extract_patches(images)

    for i in range(len(images)):

        if types[i] != "open":
            continue

        x = patches[i].reshape(-1, patches.shape[-1])
        q = q_vec[i]

        edge_index = build_graph(x)
        node_emb = qgnn(x, edge_index, q)

        keywords = extract_keywords(node_emb)
        pred = generate_answer(keywords, questions[i])

        bleu = compute_bleu(pred, answers[i])
        bleu_scores.append(bleu)

print("Average BLEU:", sum(bleu_scores)/len(bleu_scores))





